name: Daily Redis Cleanup

on:
  schedule:

    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Retry Redis cleanup endpoint up to 6 times
        run: |
          n=0
          until [ $n -ge 6 ]
          do
            echo "Attempt $((n+1))..."
            curl -s -f -X GET https://appeggio-backend.onrender.com/cron/wakeup-clean \
              -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
              && echo "Success" && break

            n=$((n+1))

            if [ $n -eq 1 ]; then
              echo "Retry $n failed. Waiting 30 seconds..."
              sleep 30
            else
              echo "Retry $n failed. Waiting 20 seconds..."
              sleep 20
            fi
          done

          if [ $n -eq 6 ]; then
            echo "All 6 attempts failed."
            exit 1
          fi

